#!/usr/bin/env bash

action=$1

function usage {
	echo "  $(basename $0)"
	echo "    List tasks that are due tomorrow"
	echo ""
	exit
}

[ "$action" = "usage" ] && usage

if [ $(uname) != "Darwin" ]
then
    TOMORROW=$(date --date="tomorrow" +%Y-%m-%d)
else
    TOMORROW=$(date -v "+1d" +%Y-%m-%d)
fi

todo.sh list | grep "due:$TOMORROW" | sed "s/due:$TOMORROW/due:tomorrow/g"
